//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FKWebBrowser.Language {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LanguageRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LanguageRes() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FKWebBrowser.Language.LanguageRes", typeof(LanguageRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 // 自动点击元素 的本地化字符串。
        /// </summary>
        internal static string Code_CommitAutoClinkElement {
            get {
                return ResourceManager.GetString("Code_CommitAutoClinkElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 // 自动填充下拉列表
        ///// Param2: 选项卡的索引号，以0开始 的本地化字符串。
        /// </summary>
        internal static string Code_CommitAutoFillDropdown {
            get {
                return ResourceManager.GetString("Code_CommitAutoFillDropdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 // 自动填充iFrame 的本地化字符串。
        /// </summary>
        internal static string Code_CommitAutoFilliFrame {
            get {
                return ResourceManager.GetString("Code_CommitAutoFilliFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 // 自动填充输入框 的本地化字符串。
        /// </summary>
        internal static string Code_CommitAutoFillTextbox {
            get {
                return ResourceManager.GetString("Code_CommitAutoFillTextbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 // 创建一个文件
        ///// Param1: 数据内容
        ///// Param2: 文件名
        ///// Param3: 若文件存在，true在尾部写入，false则覆盖原文件 的本地化字符串。
        /// </summary>
        internal static string Code_CommitCreateFile {
            get {
                return ResourceManager.GetString("Code_CommitCreateFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 // 创建文件夹 的本地化字符串。
        /// </summary>
        internal static string Code_CommitCreateFolder {
            get {
                return ResourceManager.GetString("Code_CommitCreateFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 // 查询指定元素指定属性 的本地化字符串。
        /// </summary>
        internal static string Code_CommitExtractAttribute {
            get {
                return ResourceManager.GetString("Code_CommitExtractAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 // 获取文件列表 的本地化字符串。
        /// </summary>
        internal static string Code_CommitGetFiles {
            get {
                return ResourceManager.GetString("Code_CommitGetFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 // 获取文件夹列表 的本地化字符串。
        /// </summary>
        internal static string Code_CommitGetFolders {
            get {
                return ResourceManager.GetString("Code_CommitGetFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 // 打开网页 的本地化字符串。
        /// </summary>
        internal static string Code_CommitGo {
            get {
                return ResourceManager.GetString("Code_CommitGo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 // 图片识别
        ///// Param1: 图片XPath路径
        ///// Param2: 语言类型 ( eng, chi_sim ) 的本地化字符串。
        /// </summary>
        internal static string Code_CommitImageToText {
            get {
                return ResourceManager.GetString("Code_CommitImageToText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 // 键盘按下
        ///// 参数1：键盘值( &apos;A&apos; .... &apos;Z&apos;  .... &apos;0&apos; )
        ///// 参数2：延迟多久后执行( 毫秒 ) 的本地化字符串。
        /// </summary>
        internal static string Code_CommitKeyDown {
            get {
                return ResourceManager.GetString("Code_CommitKeyDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 // 键盘松开
        ///// 参数1：键盘值( &apos;A&apos; .... &apos;Z&apos;  .... &apos;0&apos; )
        ///// 参数2：延迟多久后执行( 毫秒 ) 的本地化字符串。
        /// </summary>
        internal static string Code_CommitKeyUp {
            get {
                return ResourceManager.GetString("Code_CommitKeyUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 // 鼠标单击
        ///// 参数1：鼠标类型( Left, Middle, Right )
        ///// 参数2：延迟多久后执行( 毫秒 ) 的本地化字符串。
        /// </summary>
        internal static string Code_CommitMouseClick {
            get {
                return ResourceManager.GetString("Code_CommitMouseClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 // 鼠标双击
        ///// 参数1：鼠标类型( Left, Middle, Right )
        ///// 参数2：延迟多久后执行( 毫秒 ) 的本地化字符串。
        /// </summary>
        internal static string Code_CommitMouseDoubleClick {
            get {
                return ResourceManager.GetString("Code_CommitMouseDoubleClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 // 鼠标按下
        ///// 参数1：鼠标类型( Left, Middle, Right )
        ///// 参数2：延迟多久后执行( 毫秒 ) 的本地化字符串。
        /// </summary>
        internal static string Code_CommitMouseDown {
            get {
                return ResourceManager.GetString("Code_CommitMouseDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 // 移动鼠标
        ///// 参数1：x坐标
        ///// 参数2：y坐标
        ///// 参数3：是否移动时显示鼠标图标
        ///// 参数4：延迟多久后进行移动( 毫秒 ) 的本地化字符串。
        /// </summary>
        internal static string Code_CommitMouseMove {
            get {
                return ResourceManager.GetString("Code_CommitMouseMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 // 鼠标松开
        ///// 参数1：鼠标类型( Left, Middle, Right )
        ///// 参数2：延迟多久后执行( 毫秒 ) 的本地化字符串。
        /// </summary>
        internal static string Code_CommitMouseUp {
            get {
                return ResourceManager.GetString("Code_CommitMouseUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 // 滚轮滚动
        ///// 参数1：滚动度数
        ///// 参数2：延迟多久后执行( 毫秒 ) 的本地化字符串。
        /// </summary>
        internal static string Code_CommitMouseWheel {
            get {
                return ResourceManager.GetString("Code_CommitMouseWheel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 // 在资源管理器打开文件夹 的本地化字符串。
        /// </summary>
        internal static string Code_CommitOpenExplore {
            get {
                return ResourceManager.GetString("Code_CommitOpenExplore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 // 读Excel单元格 的本地化字符串。
        /// </summary>
        internal static string Code_CommitReadExcel {
            get {
                return ResourceManager.GetString("Code_CommitReadExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 // 删除指定文件 的本地化字符串。
        /// </summary>
        internal static string Code_CommitRemoveFile {
            get {
                return ResourceManager.GetString("Code_CommitRemoveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 // 删除文件夹 的本地化字符串。
        /// </summary>
        internal static string Code_CommitRemoveFolder {
            get {
                return ResourceManager.GetString("Code_CommitRemoveFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 // 执行命令行
        ///// Param1: 命令
        ///// Param2: 命令参数 的本地化字符串。
        /// </summary>
        internal static string Code_CommitRunCommand {
            get {
                return ResourceManager.GetString("Code_CommitRunCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 // 发送邮件 的本地化字符串。
        /// </summary>
        internal static string Code_CommitSendEmail {
            get {
                return ResourceManager.GetString("Code_CommitSendEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 // 在&quot;日志&quot;选项卡显示当前鼠标位置 的本地化字符串。
        /// </summary>
        internal static string Code_CommitShowMousePos {
            get {
                return ResourceManager.GetString("Code_CommitShowMousePos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 // 休眠
        ///// Param1: 100毫秒=1，1秒=10
        ///// Params: true需要当前网页加载完毕,false则直接等待指定时间 的本地化字符串。
        /// </summary>
        internal static string Code_CommitSleepFalse {
            get {
                return ResourceManager.GetString("Code_CommitSleepFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 // 休眠
        ///// Param1: 100毫秒=1，1秒=10
        ///// Params: true需要当前网页加载完毕,false则直接等待指定时间 的本地化字符串。
        /// </summary>
        internal static string Code_CommitSleepTrue {
            get {
                return ResourceManager.GetString("Code_CommitSleepTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 // 屏幕快照 的本地化字符串。
        /// </summary>
        internal static string Code_CommitSnapShot {
            get {
                return ResourceManager.GetString("Code_CommitSnapShot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 // 格式转换 Text-&gt;Json 的本地化字符串。
        /// </summary>
        internal static string Code_CommitTextToJson {
            get {
                return ResourceManager.GetString("Code_CommitTextToJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 // 格式转换 Text-&gt;Xml 的本地化字符串。
        /// </summary>
        internal static string Code_CommitTextToXml {
            get {
                return ResourceManager.GetString("Code_CommitTextToXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 // 写Excel单元格 的本地化字符串。
        /// </summary>
        internal static string Code_CommitWriteExcel {
            get {
                return ResourceManager.GetString("Code_CommitWriteExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 【快捷键】
        ///-------------------------------
        ///F1: 隐藏本软件。
        ///F5: 运行/停止 脚本。
        ///F6: 开始/停止 脚本记录。
        ///F12: 显示/隐藏 脚本窗口。 的本地化字符串。
        /// </summary>
        internal static string Desc_About {
            get {
                return ResourceManager.GetString("Desc_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 空白选项卡 的本地化字符串。
        /// </summary>
        internal static string EmptyTab {
            get {
                return ResourceManager.GetString("EmptyTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 脚本文件(*.fks)|*.fks 的本地化字符串。
        /// </summary>
        internal static string Filter_OpenAScriptFile {
            get {
                return ResourceManager.GetString("Filter_OpenAScriptFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 脚本文件(*.fks)|*.fks 的本地化字符串。
        /// </summary>
        internal static string Filter_SaveAScriptFile1 {
            get {
                return ResourceManager.GetString("Filter_SaveAScriptFile1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 【错误】无法找到指定页面元素。 的本地化字符串。
        /// </summary>
        internal static string Log_CanntFindElm {
            get {
                return ResourceManager.GetString("Log_CanntFindElm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 【错误】无法获得当前浏览器实例。 的本地化字符串。
        /// </summary>
        internal static string Log_CanntFindWebBrowser {
            get {
                return ResourceManager.GetString("Log_CanntFindWebBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 软件初始化完成。 的本地化字符串。
        /// </summary>
        internal static string Log_InitDone {
            get {
                return ResourceManager.GetString("Log_InitDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭代理 的本地化字符串。
        /// </summary>
        internal static string Log_NoProxy {
            get {
                return ResourceManager.GetString("Log_NoProxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 【错误】无法打开文件，错误{0}。 的本地化字符串。
        /// </summary>
        internal static string Log_OpenFileError {
            get {
                return ResourceManager.GetString("Log_OpenFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 【错误】无法保存文件，错误{0}。 的本地化字符串。
        /// </summary>
        internal static string Log_SaveFileError {
            get {
                return ResourceManager.GetString("Log_SaveFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更换代理地址为： 的本地化字符串。
        /// </summary>
        internal static string Log_UseHttpProxyIP {
            get {
                return ResourceManager.GetString("Log_UseHttpProxyIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更换代理端口为： 的本地化字符串。
        /// </summary>
        internal static string Log_UseHttpProxyPort {
            get {
                return ResourceManager.GetString("Log_UseHttpProxyPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请填写属性( 例如: id ) 的本地化字符串。
        /// </summary>
        internal static string Msgbox_Attribute {
            get {
                return ResourceManager.GetString("Msgbox_Attribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自动访问新网页吗？ 的本地化字符串。
        /// </summary>
        internal static string Msgbox_ConfirmGoWebsite {
            get {
                return ResourceManager.GetString("Msgbox_ConfirmGoWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否希望休眠到网页加载完毕？ 的本地化字符串。
        /// </summary>
        internal static string Msgbox_ConfirmSleep {
            get {
                return ResourceManager.GetString("Msgbox_ConfirmSleep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前鼠标坐标为: 的本地化字符串。
        /// </summary>
        internal static string Msgbox_CurPos {
            get {
                return ResourceManager.GetString("Msgbox_CurPos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请填写下拉列表单元编号: 的本地化字符串。
        /// </summary>
        internal static string Msgbox_Dropdown {
            get {
                return ResourceManager.GetString("Msgbox_Dropdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入iFrame填充内容: 的本地化字符串。
        /// </summary>
        internal static string Msgbox_iFrame {
            get {
                return ResourceManager.GetString("Msgbox_iFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提示 的本地化字符串。
        /// </summary>
        internal static string Msgbox_Message {
            get {
                return ResourceManager.GetString("Msgbox_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 休眠时间（100毫秒 = 1）： 的本地化字符串。
        /// </summary>
        internal static string Msgbox_SleepInfo {
            get {
                return ResourceManager.GetString("Msgbox_SleepInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请填写输入框内容: 的本地化字符串。
        /// </summary>
        internal static string Msgbox_Textbox {
            get {
                return ResourceManager.GetString("Msgbox_Textbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 网址： 的本地化字符串。
        /// </summary>
        internal static string Msgbox_Website {
            get {
                return ResourceManager.GetString("Msgbox_Website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 脚本正在运行... 的本地化字符串。
        /// </summary>
        internal static string Tip_BeginRunScript {
            get {
                return ResourceManager.GetString("Tip_BeginRunScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 脚本运行完毕。 的本地化字符串。
        /// </summary>
        internal static string Tip_CompleteRunScript {
            get {
                return ResourceManager.GetString("Tip_CompleteRunScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在休眠...:   的本地化字符串。
        /// </summary>
        internal static string Tip_Sleeping {
            get {
                return ResourceManager.GetString("Tip_Sleeping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建新脚本文件完成... 的本地化字符串。
        /// </summary>
        internal static string Tips_CreateScript {
            get {
                return ResourceManager.GetString("Tips_CreateScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件只读，保存失败。 的本地化字符串。
        /// </summary>
        internal static string Tips_FileReadOnly {
            get {
                return ResourceManager.GetString("Tips_FileReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件保存成功。 的本地化字符串。
        /// </summary>
        internal static string Tips_FileSaved {
            get {
                return ResourceManager.GetString("Tips_FileSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 后台运行中...单击图标可恢复 的本地化字符串。
        /// </summary>
        internal static string Tips_MinAppNotify {
            get {
                return ResourceManager.GetString("Tips_MinAppNotify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存脚本文件... 的本地化字符串。
        /// </summary>
        internal static string Tips_SaveScript {
            get {
                return ResourceManager.GetString("Tips_SaveScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 账号 的本地化字符串。
        /// </summary>
        internal static string UI_AccountMenu {
            get {
                return ResourceManager.GetString("UI_AccountMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 后退 的本地化字符串。
        /// </summary>
        internal static string UI_BackMenu {
            get {
                return ResourceManager.GetString("UI_BackMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清空 的本地化字符串。
        /// </summary>
        internal static string UI_ClearScriptBtn {
            get {
                return ResourceManager.GetString("UI_ClearScriptBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭全部选项卡 的本地化字符串。
        /// </summary>
        internal static string UI_CloseAllTabMenu {
            get {
                return ResourceManager.GetString("UI_CloseAllTabMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭当前选项卡 的本地化字符串。
        /// </summary>
        internal static string UI_CloseTabMenu {
            get {
                return ResourceManager.GetString("UI_CloseTabMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 高级功能 的本地化字符串。
        /// </summary>
        internal static string UI_ContextMenu_Advanced {
            get {
                return ResourceManager.GetString("UI_ContextMenu_Advanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图片识别 的本地化字符串。
        /// </summary>
        internal static string UI_ContextMenu_Advanced_ImageToText {
            get {
                return ResourceManager.GetString("UI_ContextMenu_Advanced_ImageToText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 读Excel单元格 的本地化字符串。
        /// </summary>
        internal static string UI_ContextMenu_Advanced_ReadExcel {
            get {
                return ResourceManager.GetString("UI_ContextMenu_Advanced_ReadExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 控制台命令 的本地化字符串。
        /// </summary>
        internal static string UI_ContextMenu_Advanced_RunCommand {
            get {
                return ResourceManager.GetString("UI_ContextMenu_Advanced_RunCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发送邮件 的本地化字符串。
        /// </summary>
        internal static string UI_ContextMenu_Advanced_SendEmail {
            get {
                return ResourceManager.GetString("UI_ContextMenu_Advanced_SendEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全屏截屏 的本地化字符串。
        /// </summary>
        internal static string UI_ContextMenu_Advanced_TakeSnapShot {
            get {
                return ResourceManager.GetString("UI_ContextMenu_Advanced_TakeSnapShot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 格式转换Text-&gt;Json 的本地化字符串。
        /// </summary>
        internal static string UI_ContextMenu_Advanced_TextToJson {
            get {
                return ResourceManager.GetString("UI_ContextMenu_Advanced_TextToJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 格式转换Text-&gt;Xml 的本地化字符串。
        /// </summary>
        internal static string UI_ContextMenu_Advanced_TextToXml {
            get {
                return ResourceManager.GetString("UI_ContextMenu_Advanced_TextToXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 写Excel单元格 的本地化字符串。
        /// </summary>
        internal static string UI_ContextMenu_Advanced_WriteExcel {
            get {
                return ResourceManager.GetString("UI_ContextMenu_Advanced_WriteExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 基本功能 的本地化字符串。
        /// </summary>
        internal static string UI_ContextMenu_Base {
            get {
                return ResourceManager.GetString("UI_ContextMenu_Base", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建文件 的本地化字符串。
        /// </summary>
        internal static string UI_ContextMenu_Base_CreateFile {
            get {
                return ResourceManager.GetString("UI_ContextMenu_Base_CreateFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建文件夹 的本地化字符串。
        /// </summary>
        internal static string UI_ContextMenu_Base_CreateFolder {
            get {
                return ResourceManager.GetString("UI_ContextMenu_Base_CreateFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取文件列表 的本地化字符串。
        /// </summary>
        internal static string UI_ContextMenu_Base_GetFiles {
            get {
                return ResourceManager.GetString("UI_ContextMenu_Base_GetFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取文件夹列表 的本地化字符串。
        /// </summary>
        internal static string UI_ContextMenu_Base_GetFolders {
            get {
                return ResourceManager.GetString("UI_ContextMenu_Base_GetFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开文件夹 的本地化字符串。
        /// </summary>
        internal static string UI_ContextMenu_Base_OpenExplore {
            get {
                return ResourceManager.GetString("UI_ContextMenu_Base_OpenExplore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除文件 的本地化字符串。
        /// </summary>
        internal static string UI_ContextMenu_Base_RemoveFile {
            get {
                return ResourceManager.GetString("UI_ContextMenu_Base_RemoveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除文件夹 的本地化字符串。
        /// </summary>
        internal static string UI_ContextMenu_Base_RemoveFolder {
            get {
                return ResourceManager.GetString("UI_ContextMenu_Base_RemoveFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据库 的本地化字符串。
        /// </summary>
        internal static string UI_ContextMenu_Database {
            get {
                return ResourceManager.GetString("UI_ContextMenu_Database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提取元素属性 的本地化字符串。
        /// </summary>
        internal static string UI_ContextMenu_Extract {
            get {
                return ResourceManager.GetString("UI_ContextMenu_Extract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提取指定属性 的本地化字符串。
        /// </summary>
        internal static string UI_ContextMenu_Extract_Attribute {
            get {
                return ResourceManager.GetString("UI_ContextMenu_Extract_Attribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提取Html属性 的本地化字符串。
        /// </summary>
        internal static string UI_ContextMenu_Extract_Html {
            get {
                return ResourceManager.GetString("UI_ContextMenu_Extract_Html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提取Src属性 的本地化字符串。
        /// </summary>
        internal static string UI_ContextMenu_Extract_Src {
            get {
                return ResourceManager.GetString("UI_ContextMenu_Extract_Src", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取文本属性 的本地化字符串。
        /// </summary>
        internal static string UI_ContextMenu_Extract_Text {
            get {
                return ResourceManager.GetString("UI_ContextMenu_Extract_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取超链接属性 的本地化字符串。
        /// </summary>
        internal static string UI_ContextMenu_Extract_Url {
            get {
                return ResourceManager.GetString("UI_ContextMenu_Extract_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 填充点击 的本地化字符串。
        /// </summary>
        internal static string UI_ContextMenu_Fill {
            get {
                return ResourceManager.GetString("UI_ContextMenu_Fill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 点击元素 的本地化字符串。
        /// </summary>
        internal static string UI_ContextMenu_Fill_ClickElement {
            get {
                return ResourceManager.GetString("UI_ContextMenu_Fill_ClickElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 填充下拉列表 的本地化字符串。
        /// </summary>
        internal static string UI_ContextMenu_Fill_Dropdown {
            get {
                return ResourceManager.GetString("UI_ContextMenu_Fill_Dropdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 填充iFrame 的本地化字符串。
        /// </summary>
        internal static string UI_ContextMenu_Fill_iFrame {
            get {
                return ResourceManager.GetString("UI_ContextMenu_Fill_iFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 填充输入框 的本地化字符串。
        /// </summary>
        internal static string UI_ContextMenu_Fill_Textbox {
            get {
                return ResourceManager.GetString("UI_ContextMenu_Fill_Textbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 访问网址 的本地化字符串。
        /// </summary>
        internal static string UI_ContextMenu_Go {
            get {
                return ResourceManager.GetString("UI_ContextMenu_Go", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按键模拟 的本地化字符串。
        /// </summary>
        internal static string UI_ContextMenu_Keyboard {
            get {
                return ResourceManager.GetString("UI_ContextMenu_Keyboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按键按下 的本地化字符串。
        /// </summary>
        internal static string UI_ContextMenu_Keyboard_KeyDown {
            get {
                return ResourceManager.GetString("UI_ContextMenu_Keyboard_KeyDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按键松开 的本地化字符串。
        /// </summary>
        internal static string UI_ContextMenu_Keyboard_KeyUp {
            get {
                return ResourceManager.GetString("UI_ContextMenu_Keyboard_KeyUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 鼠标模拟 的本地化字符串。
        /// </summary>
        internal static string UI_ContextMenu_Mouse {
            get {
                return ResourceManager.GetString("UI_ContextMenu_Mouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取鼠标坐标 的本地化字符串。
        /// </summary>
        internal static string UI_ContextMenu_Mouse_GetCurrentMouse {
            get {
                return ResourceManager.GetString("UI_ContextMenu_Mouse_GetCurrentMouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 鼠标点击 的本地化字符串。
        /// </summary>
        internal static string UI_ContextMenu_Mouse_MouseClick {
            get {
                return ResourceManager.GetString("UI_ContextMenu_Mouse_MouseClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 鼠标双击 的本地化字符串。
        /// </summary>
        internal static string UI_ContextMenu_Mouse_MouseDoubleClick {
            get {
                return ResourceManager.GetString("UI_ContextMenu_Mouse_MouseDoubleClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 鼠标按下 的本地化字符串。
        /// </summary>
        internal static string UI_ContextMenu_Mouse_MouseDown {
            get {
                return ResourceManager.GetString("UI_ContextMenu_Mouse_MouseDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 鼠标移动 的本地化字符串。
        /// </summary>
        internal static string UI_ContextMenu_Mouse_MouseMove {
            get {
                return ResourceManager.GetString("UI_ContextMenu_Mouse_MouseMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 鼠标松开 的本地化字符串。
        /// </summary>
        internal static string UI_ContextMenu_Mouse_MouseUp {
            get {
                return ResourceManager.GetString("UI_ContextMenu_Mouse_MouseUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 鼠标滚轮滚动 的本地化字符串。
        /// </summary>
        internal static string UI_ContextMenu_Mouse_MouseWheel {
            get {
                return ResourceManager.GetString("UI_ContextMenu_Mouse_MouseWheel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 休眠等待 的本地化字符串。
        /// </summary>
        internal static string UI_ContextMenu_Sleep {
            get {
                return ResourceManager.GetString("UI_ContextMenu_Sleep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 访问 的本地化字符串。
        /// </summary>
        internal static string UI_GoBtn {
            get {
                return ResourceManager.GetString("UI_GoBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登录 的本地化字符串。
        /// </summary>
        internal static string UI_LoginAccountMenu {
            get {
                return ResourceManager.GetString("UI_LoginAccountMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 注销 的本地化字符串。
        /// </summary>
        internal static string UI_LogoutAccountMenu {
            get {
                return ResourceManager.GetString("UI_LogoutAccountMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 日志 的本地化字符串。
        /// </summary>
        internal static string UI_LogTabPage {
            get {
                return ResourceManager.GetString("UI_LogTabPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MP 的本地化字符串。
        /// </summary>
        internal static string UI_MPTabPage {
            get {
                return ResourceManager.GetString("UI_MPTabPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新建 的本地化字符串。
        /// </summary>
        internal static string UI_NewScriptMenu {
            get {
                return ResourceManager.GetString("UI_NewScriptMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新建选项卡 的本地化字符串。
        /// </summary>
        internal static string UI_NewTabMenu {
            get {
                return ResourceManager.GetString("UI_NewTabMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 前进 的本地化字符串。
        /// </summary>
        internal static string UI_NextMenu {
            get {
                return ResourceManager.GetString("UI_NextMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开 的本地化字符串。
        /// </summary>
        internal static string UI_OpenScriptMenu {
            get {
                return ResourceManager.GetString("UI_OpenScriptMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 录制 的本地化字符串。
        /// </summary>
        internal static string UI_RecordBtn {
            get {
                return ResourceManager.GetString("UI_RecordBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 刷新 的本地化字符串。
        /// </summary>
        internal static string UI_RefreshMenu {
            get {
                return ResourceManager.GetString("UI_RefreshMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 注册 的本地化字符串。
        /// </summary>
        internal static string UI_RegisterAccountMenu {
            get {
                return ResourceManager.GetString("UI_RegisterAccountMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 运行 的本地化字符串。
        /// </summary>
        internal static string UI_RunScriptBtn {
            get {
                return ResourceManager.GetString("UI_RunScriptBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 另存为... 的本地化字符串。
        /// </summary>
        internal static string UI_SaveAsScriptMenu {
            get {
                return ResourceManager.GetString("UI_SaveAsScriptMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存 的本地化字符串。
        /// </summary>
        internal static string UI_SaveScriptMenu {
            get {
                return ResourceManager.GetString("UI_SaveScriptMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 脚本 的本地化字符串。
        /// </summary>
        internal static string UI_ScriptMenu {
            get {
                return ResourceManager.GetString("UI_ScriptMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 脚本编辑器 的本地化字符串。
        /// </summary>
        internal static string UI_ScriptTabPage {
            get {
                return ResourceManager.GetString("UI_ScriptTabPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 脚本编辑窗 的本地化字符串。
        /// </summary>
        internal static string UI_ScriptWindowMenu {
            get {
                return ResourceManager.GetString("UI_ScriptWindowMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关于 的本地化字符串。
        /// </summary>
        internal static string UI_SettingAboutMenu {
            get {
                return ResourceManager.GetString("UI_SettingAboutMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开启/关闭 Flash 的本地化字符串。
        /// </summary>
        internal static string UI_SettingFlashMenu {
            get {
                return ResourceManager.GetString("UI_SettingFlashMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 隐藏应用 的本地化字符串。
        /// </summary>
        internal static string UI_SettingHideAppMenu {
            get {
                return ResourceManager.GetString("UI_SettingHideAppMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 英语 的本地化字符串。
        /// </summary>
        internal static string UI_SettingLangEN_USMenu {
            get {
                return ResourceManager.GetString("UI_SettingLangEN_USMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 语言设置 的本地化字符串。
        /// </summary>
        internal static string UI_SettingLanguageMenu {
            get {
                return ResourceManager.GetString("UI_SettingLanguageMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 简体中文 的本地化字符串。
        /// </summary>
        internal static string UI_SettingLangZH_CNMenu {
            get {
                return ResourceManager.GetString("UI_SettingLangZH_CNMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置 的本地化字符串。
        /// </summary>
        internal static string UI_SettingMenu {
            get {
                return ResourceManager.GetString("UI_SettingMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 停止 的本地化字符串。
        /// </summary>
        internal static string UI_StopScriptBtn {
            get {
                return ResourceManager.GetString("UI_StopScriptBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TPP 的本地化字符串。
        /// </summary>
        internal static string UI_TPPTabPage {
            get {
                return ResourceManager.GetString("UI_TPPTabPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 视图 的本地化字符串。
        /// </summary>
        internal static string UI_ViewMenu {
            get {
                return ResourceManager.GetString("UI_ViewMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FreeKnight浏览器 的本地化字符串。
        /// </summary>
        internal static string WndTiltle_AppName {
            get {
                return ResourceManager.GetString("WndTiltle_AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关于 的本地化字符串。
        /// </summary>
        internal static string WndTitle_About {
            get {
                return ResourceManager.GetString("WndTitle_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 版本号 的本地化字符串。
        /// </summary>
        internal static string WndTitle_AppVersionDesc {
            get {
                return ResourceManager.GetString("WndTitle_AppVersionDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开一个脚本文件 的本地化字符串。
        /// </summary>
        internal static string WndTitle_OpenAScriptFile {
            get {
                return ResourceManager.GetString("WndTitle_OpenAScriptFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存一个脚本文件 的本地化字符串。
        /// </summary>
        internal static string WndTitle_SaveAScriptFile1 {
            get {
                return ResourceManager.GetString("WndTitle_SaveAScriptFile1", resourceCulture);
            }
        }
    }
}
